package controllers;

import play.data.Form;
import play.data.validation.Constraints.Required;
import play.mvc.Controller;
import play.mvc.Result;

import views.html.*;

public class Login extends Controller {

	static Form<Login.LoginModel> loginForm = Form.form(Login.LoginModel.class);

	public static Result form() {
		return ok(login.render(loginForm));
	}

	/* NOTE: Login is implemented only rudimentary (because it's a horizontal prototype, 
	 * so only simple session management was applied. Session cookies are generated by the
	 * play framework by signing the cookies data. As there is only the username stored in the
	 * cookie, its content is static and if an attacker gets access to the cookie once, he 
	 * will be able to login with the corresponding user permanently. Should be fixed 
	 * when going productive. */
	public static Result login() {
		System.out.println("login");
		Form<Login.LoginModel> formLm = loginForm.bindFromRequest("username",
				"password");

		if (formLm.hasErrors()) {
			flash("failed", "failed");
			return badRequest(login.render(loginForm));
		}

		// STATIC PASSWORD COMPARISON
		if (formLm.field("username").value().equals("waecm")
				&& formLm.field("password").value().equals("waecm")) {
			System.out.println("correct login");
			session().clear();
	        session("username", formLm.field("username").value());
			return redirect(routes.Application.index());
		} else {
			flash("wrongCredentials", "failed");
		}

		return ok(login.render(loginForm));
	}
	
	public static Result logout() {
		session().clear();
		return redirect(routes.Application.index());
	}

	public static class LoginModel {
		@Required
		public String username;
		@Required
		public String password;
	}
}
